name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Install wasm32 target
        run: |
          rustup toolchain install stable --target wasm32-unknown-unknown

      - name: Check rustfmt
        run:
          cargo fmt --all -- --check

      - name: Check
        run: |
          cargo check

      - name: Check examples
        run: |
          cargo check --manifest-path examples/basic/Cargo.toml
          cargo check --manifest-path examples/custom/Cargo.toml

      - name: Test
        run: |
          cargo test

      - name: Install binstall
        run: |
          curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash

      - name: Install cargo-all-features
        run: |
          cargo binstall -y cargo-all-features

      - name: Check all features
        run: |
          cargo check-all-features --target wasm32-unknown-unknown
